# Generated by Django 4.2.6 on 2024-02-05 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='visibility',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
